version: "3"

networks:
  default-network:
    driver: bridge

services:
  database:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=erivaldo
      - POSTGRES_DB=rentxDB
      - POSTGRES_USER=erivaldo
    networks:
      - default-network

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - database
    networks:
      - default-network
    environment:
      - DATABASE_URL=postgresql://erivaldo:erivaldo@postgres:5432/rentxDB?schema=public

volumes:
  pgdata:
